# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1
# and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence
# whose values do not exceed four million, find the
# sum of the even-valued terms.
#================================================
fib_arr = [1,2]

def fibonacci_builder(arr, limit)
  new_num = arr[-1] + arr[-2]
  if new_num > limit
    return arr
  else
    arr.push(new_num)
    fibonacci_builder(arr, 4_000_000)
  end
end

fib_to_4_mil = fibonacci_builder(fib_arr, 4_000_000)
answer = fib_to_4_mil.select(&:even?).reduce(:+)

puts answer



