# Triangle numbers are generated by adding the natural numbers
# between 1 and itself. Knowing this, we determine the 7th
# triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

# What's the value of the 1st triangle num
# with > five hundred divisors?

def five_hundred_divisors?(num)
  divisors = []
  for i in 1..num
    divisors << i if num % i == 0
  end
  return false if divisors.uniq.size <= 500
  return true
end

triangle_nums = [1]

while five_hundred_divisors?(triangle_nums.last) == false do
  new_num = triangle_nums.last + triangle_nums.size + 1
  triangle_nums.push(new_num)
  puts new_num
  puts "The answer to Problem 12 is #{new_num}" if five_hundred_divisors?(triangle_nums.last)
end

